### ISSUE TITLE
User should be able to create PTS config on request page

### ISSUE THREAD

**Issue by scroodge** [aliaksandr-aliakseyeu/Schedule#16]
Add possibility to create own configuration from this menu as popup.
![image](https://github.com/Gollum959/Schedule/assets/1701571/c89f4945-7074-496e-8c59-286fdf903b0b)

**Comment by Gollum959** [comment]
Our behavior if we don't have a base configuration and we aren't headmaster? Can you describe what you want to see, page with choices or page with form based on base configuration?

**Comment by scroodge** [comment]
If there is no base configuration - user should stop doing request (this will be change in next version)  so if Base config is exist - user will see popup with base config - if base config is not what user want - it should be button "Create User Base config" - the new popup - where user create new base config and save it. After all this steps this new base config should be in the Config PT list

**Comment by scroodge** [comment]
Button is not clickable 
![image](https://github.com/Gollum959/Schedule/assets/1701571/f7f37fc5-af20-4c8d-8d94-97e323dcb7e2)

**Comment by Gollum959** [comment]
now you can only create cfg on base, so I think we haven't had base cfg. Please describe how you see this function for main director

**Comment by scroodge** [comment]
Good solution! Can you please make a remark on this icon. User point to icon and got a popup with text - there is no Base config - please create
