### ISSUE TITLE
New field in Request (Director on site)

### ISSUE THREAD

**Issue by scroodge** [aliaksandr-aliakseyeu/Schedule#17]
Create Field with Director list ( initial values is Logged User). If logged User is not Real Director - than user can select a director from the list.
![image](https://github.com/Gollum959/Schedule/assets/1701571/2680fa61-e9b5-4cc8-9c2f-e036ebf6acc4)

**Comment by Gollum959** [comment]
can only the main director or any director do this?

**Comment by Gollum959** [comment]
Do I need to show the author of the request somewhere?

**Comment by scroodge** [comment]
Yes in list Согласование

**Comment by scroodge** [comment]
Implemented
