### ISSUE TITLE
Director DTOV, GDTP,Soundman

### ISSUE THREAD

**Issue by scroodge** [aliaksandr-aliakseyeu/Schedule#26]
This users can't create any of this 
![image](https://github.com/Gollum959/Schedule/assets/1701571/2c34fa78-fd01-4697-812a-ebbc4074466c)

**Comment by Gollum959** [comment]
Should I remove these links for such users?

**Comment by scroodge** [comment]
Yes

**Comment by scroodge** [comment]
PLease remove this options also from Начальник ПТС
