### ISSUE TITLE
Add commentary position

### ISSUE THREAD

**Issue by scroodge** [aliaksandr-aliakseyeu/Schedule#31]
Add to configuration - Commentary position as follows
![image](https://github.com/Gollum959/Schedule/assets/1701571/e5dd78e5-2652-4334-b1ff-c37746df2403)

**Comment by Gollum959** [comment]
Do you want just two check box true or false?

**Comment by scroodge** [comment]
Add Commentary textBox - to add some more text

**Comment by Gollum959** [comment]
Now in DB we have this 3 fields
![image](https://github.com/Gollum959/Schedule/assets/93978019/7b564b33-4c70-4cf9-bcb8-7b88e89a2be9)

**Comment by scroodge** [comment]
So this fields will be used to calculate number of equipment in OB Van.
For task above i propose to make additional fields or blocks.
