### ISSUE TITLE
Logic to add in new request Base config

### ISSUE THREAD

**Issue by scroodge** [aliaksandr-aliakseyeu/Schedule#32]
Now when you click 
![image](https://github.com/Gollum959/Schedule/assets/1701571/cfea8476-f0af-4d98-b4b3-459129438624)
You go to new page and create base config. When you created base config - you have only one option - close page - so you will come back to your initial request - but you couldn't find your created base config.

Please propose solution

**Comment by Gollum959** [comment]
I apologize for my confusion. If you want to automatically add base configuration I'll do it using pop up(not new tab) window but it'll be without modal(alert window) window.

**Comment by Gollum959** [comment]
Or I can add button like refresh button next to the button create
![image](https://github.com/Gollum959/Schedule/assets/93978019/010a97d7-405c-4316-a2a1-495b24e7ea3e)

**Comment by scroodge** [comment]
As far as i see now - i need to close parent window to update configs. 
1. Can we update it when new config is created?
2. If not - can we close request page?
